data:
  data_keys: ['metr-la', 'pems-bay', 'shenzhen', 'chengdu_m']
  metr-la:
    dataset_path: data/metr-la/dataset_expand.npy
    adjacency_matrix_path: data/metr-la/matrix.npy
    time_step: 34272
    node_num: 207
    speed_mean: 58.465786
    speed_std: 12.905341
  
  pems-bay:
    dataset_path: data/pems-bay/dataset_expand.npy
    adjacency_matrix_path: data/pems-bay/matrix.npy
    time_step: 52116
    node_num: 325
    speed_mean: 62.621582859
    speed_std: 9.58811369696

  chengdu_m:
    dataset_path: data/chengdu_m/dataset_expand.npy
    adjacency_matrix_path: data/chengdu_m/matrix.npy
    time_step: 17280
    node_num: 524
    speed_mean: 29.0982979559
    speed_std: 9.75304346669
  
  shenzhen:
    dataset_path: data/shenzhen/dataset_expand.npy
    adjacency_matrix_path: data/shenzhen/matrix.npy
    time_step: 17280
    node_num: 627
    speed_mean: 30.5735608506
    speed_std: 11.0922606598
  
task:
  source:
    his_num: 288
    pred_num: 36
    batch_size: 16
    task_num: 2
    add_target : True  # not used in source training finally
  target_few_shot:
      add_target: true
      batch_size: 46
      his_num: 288
      pred_num: 36
      task_num: 2

model:
  STnet:
    #target_lr : 0.0001
    lr : 0.001
